<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
def matrix(a, b):
    if len(a[0]) != len(b):
        return print("multiplication not possible")

    line = []

    fly = len(b[0]) * [0]
    for r in range(len(a)):
        line.append(fly[:])
    for str in range(len(a)):
        for clmn in range(len(b[0])):
            sum = 0
            for k in range(len(a[0])):
                sum = sum + a[str][k] * b[k][clmn]
            line[str][clmn] = sum
    return line
wed=[[1,3,4],[2,5,7],[5,9,6]]
word=[[1,0,0],[0,1,0],[0,0,1]]

print(matrix(wed,word))

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
import random
from itertools import accumulate
import bisect

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
A=sorted(A)


def propotional_sampling(A, n=100):
    sum = 0
    for i in range(len(A)):
        sum = sum + A[i]

    d_dash = []

    for j in range(len(A)):
        d_dash.append((A[j] / sum))

    # cumulative sum

    d_bar = [*accumulate(d_dash)]
    out = []
    for _ in range(n):
        i = random.uniform(0.0, 1.0)
        idx = bisect.bisect_right(d_bar, i)
        print(A[idx])

propotional_sampling(A)


10
10
100
100
79
79
79
28
45
100
45
100
100
100
27
28
100
79
100
79
45
79
5
100
79
100
45
6
28
45
100
100
10
45
79
45
79
100
27
27
45
100
100
79
45
100
45
79
100
79
27
45
28
79
100
27
100
79
27
13
100
45
79
100
100
100
10
79
100
100
79
5
13
45
100
45
100
100
79
100
100
10
100
100
100
79
27
100
100
100
100
79
79
79
28
13
79
100
100
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
def replace_digit(n):
        file=re.findall("[0-9]",n)
        for word in file:
            print("#",end="")
        if file==[]:
            print("(emty string)")
n=input("Enter the statement")
k=replace_digit(n)


Enter the statement56jkjl89
####

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [7]:
import operator
import itertools
def dashbord(n,m):
    dic=dict()
    for i in range(len(n)):
        dic[n[i]]=m[i]
    return dic
def greater(x,y):
    hk=dashbord(x,y)
    file=sorted(hk.items(),key=operator.itemgetter(1))
    print("\nLeast rank holder")
    for key,value in file[0:5]:
        print(key,value)


def smaller(x,y):
    kl=dashbord(x,y)
    file=sorted(kl.items(),key=operator.itemgetter(1),reverse=True)
    print("\nTop rank holder")
    for key, value in file[0:5]:
        print(key,value)

def great_small(x,y):
    jk=dashbord(x,y)
    file=sorted(jk.items(),key=operator.itemgetter(1))
    print("\nRank holder between >25 and <75 percent")
    max,min=100,0
    diff=max-min
    output=[item for item in file if item[1]>(diff*0.25) and item[1]<(diff*0.75)]
    for key,value in output:
        print(key,value)

value=("stu0","stu1","stu2","stu3","stu4","stu5","stu6","stu7","stu8","stu9")
values=(45,78,12,14,48,43,47,98,35,80)
greater(value,values)
smaller(value,values)
great_small(value,values)



Least rank holder
stu2 12
stu3 14
stu8 35
stu5 43
stu0 45

Top rank holder
stu7 98
stu9 80
stu1 78
stu4 48
stu6 47

Rank holder between >25 and <75 percent
stu8 35
stu5 43
stu0 45
stu6 47
stu4 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math
import operator
def close_point(Q,S):
    dic=dict()
    for i in S:
        x,y=i[0],i[1]
        p,q=Q[0],Q[1]
        kl = ((math.sqrt(x ** 2 + y ** 2))*(math.sqrt(p**2+q**2)))
        lk =((x*p)+(y*q))
        file=math.acos(lk/kl)
        dic[x,y]=(file)
    print("The first five shortest distance is: ")
    fly=sorted(dic.items(),key=operator.itemgetter(1))
    for key,value in fly[0:5]:
        print(key,value)
A=(3,-4)
B=[(1,-1),(3,4),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,2)]
close_point(A,B)

The first five shortest distance is: 
(6, -7) 0.06512516333438509
(1, -1) 0.14189705460416438
(6, 0) 0.9272952180016123
(-5, -8) 1.2021004241368467
(-1, -1) 1.4288992721907328


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
lst=list()
st=list()
def positive(R,B,L):
    for space in L:
        lst = list()
        a,b,c= re.findall("[0-9.\-\+]+",space)
        u,v,j=float(a),float(b),float(c)
        for line in R:
            x, y = line[0], line[1]
            z = x,y
            if y*v+u*x>j:
                lst.append(z)
            else:
                continue
        for word in B:
            d,e = word[0], word[1]
            w = d,e
            if d*a+e*b>c:
                st.append(w)
            else:
                continue
        if lst==R and st==B:
            print("False")
        elif lst==R:
            print("True")
        elif lst==B:
            print("True")
        else:
            print("false")
Red=[(1,1),(2,1),(4,2),(2,4),(-1,4)]
Blue=[(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y=0","1x-1y=0","1x+0y=3","0x+1y=0.5"]
positive(Red,Blue,Lines)

True
false
false
True


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
import copy
def missing(o):
    a = o.split(',')
    p=len(a)
    j=1
    for i in range(len(a)):
        if a[i]=='_':
            j+=1
        else:
            for h in range(j):
              a[h]=(float(a[i])/(j))
            word=a[h]
            break
    for l in range(j,len(a)):
        if a[l]=='_':
            j+=1
        else:
            for k in range(i,j+1):
                a[k]=(word+float(a[j]))/(j-i+1)
            line=a[k]
            break
    for d in range(l,len(a)):
        a[d]=(line/(p-j))
    print(a)
value="_,_,30,_,_,_,50,_,_"
missing(value)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

dic1 = {'F1S1':0,'F2S1':0,'F3S1':0,'F4S1':0,'F5S1':0,'F1S2':0,'F2S2':0,'F3S2':0,'F4S2':0,'F5S2':0,'F1S3':0,'F2S3':0,'F3S3':0,'F4S3':0,'F5S3':0}

dic2= {'S1':0,'S2':0,'S3':0}
for i in range(len(A)):
    if(A[i][0]=='F1'and A[i][1]=='S1'):
            dic1['F1S1'] = dic1['F1S1']+1
            dic2['S1'] = dic2['S1']+1
    if(A[i][0]=='F1'and A[i][1]=='S2'):
            dic1['F1S2'] = dic1['F1S2']+1
            dic2['S2'] = dic2['S2']+1
    if(A[i][0]=='F1'and A[i][1]=='S3'):
            dic1['F1S3'] = dic1['F1S3']+1
            dic2['S3'] = dic2['S3']+1
    if(A[i][0]=='F2'and A[i][1]=='S1'):
            dic1['F2S1'] = dic1['F2S1']+1
            dic2['S1'] = dic2['S1']+1
    if(A[i][0]=='F2'and A[i][1]=='S2'):
            dic1['F2S2'] = dic1['F2S2']+1
            dic2['S2'] = dic2['S2']+1
    if(A[i][0]=='F2'and A[i][1]=='S3'):
            dic1['F2S3'] = dic1['F2S3']+1
            dic2['S3'] = dic2['S3']+1
    if(A[i][0]=='F3'and A[i][1]=='S1'):
            dic1['F3S1'] = dic1['F3S1']+1
            dic2['S1'] = dic2['S1']+1
    if(A[i][0]=='F3'and A[i][1]=='S2'):
            dic1['F3S2'] = dic1['F3S2']+1
            dic2['S2'] = dic2['S2']+1
    if(A[i][0]=='F3'and A[i][1]=='S3'):
            dic1['F3S3'] = dic1['F3S3']+1
            dic2['S3'] = dic2['S3']+1
    if(A[i][0]=='F4'and A[i][1]=='S1'):
            dic1['F4S1'] = dic1['F4S1']+1
            dic2['S1'] = dic2['S1']+1
    if(A[i][0]=='F4'and A[i][1]=='S2'):
            dic1['F4S2'] = dic1['F4S2']+1
            dic2['S2'] = dic2['S2']+1
    if(A[i][0]=='F4'and A[i][1]=='S3'):
            dic1['F4S3'] = dic1['F4S3']+1
            dic2['S3'] = dic2['S3']+1
    if(A[i][0]=='F5'and A[i][1]=='S1'):
            dic1['F5S1'] = dic1['F5S1']+1
            dic2['S1'] = dic2['S1']+1
    if(A[i][0]=='F5'and A[i][1]=='S2'):
            dic1['F5S2'] = dic1['F5S2']+1
            dic2['S2'] = dic2['S2']+1
    if(A[i][0]=='F5'and A[i][1]=='S3'):
            dic1['F5S3'] = dic1['F5S3']+1
            dic2['S3'] = dic2['S3']+1
print('Probability of P(F=F1|S==S1) =',(dic1['F1S1']/dic2['S1']))
print('Probability of P(F=F1|S==S2) =',(dic1['F1S2']/dic2['S2']))
print('Probability of P(F=F1|S==S3) =',(dic1['F1S3']/dic2['S3']))
print('Probability of P(F=F2|S==S1) =',(dic1['F2S1']/dic2['S1']))
print('Probability of P(F=F2|S==S2) =',(dic1['F2S2']/dic2['S2']))
print('Probability of P(F=F2|S==S3) =',(dic1['F2S3']/dic2['S3']))
print('Probability of P(F=F3|S==S1) =',(dic1['F3S1']/dic2['S1']))
print('Probability of P(F=F3|S==S2) =',(dic1['F3S2']/dic2['S2']))
print('Probability of P(F=F3|S==S3) =',(dic1['F3S3']/dic2['S3']))
print('Probability of P(F=F4|S==S1) =',(dic1['F4S1']/dic2['S1']))
print('Probability of P(F=F4|S==S2) =',(dic1['F4S2']/dic2['S2']))
print('Probability of P(F=F4|S==S3) =',(dic1['F4S3']/dic2['S3']))
print('Probability of P(F=F5|S==S1) =',(dic1['F5S1']/dic2['S1']))
print('Probability of P(F=F5|S==S2) =',(dic1['F5S2']/dic2['S2']))
print('Probability of P(F=F5|S==S3) =',(dic1['F5S3']/dic2['S3']))

Probability of P(F=F1|S==S1) = 0.25
Probability of P(F=F1|S==S2) = 0.3333333333333333
Probability of P(F=F1|S==S3) = 0.0
Probability of P(F=F2|S==S1) = 0.25
Probability of P(F=F2|S==S2) = 0.3333333333333333
Probability of P(F=F2|S==S3) = 0.3333333333333333
Probability of P(F=F3|S==S1) = 0.0
Probability of P(F=F3|S==S2) = 0.3333333333333333
Probability of P(F=F3|S==S3) = 0.3333333333333333
Probability of P(F=F4|S==S1) = 0.25
Probability of P(F=F4|S==S2) = 0.0
Probability of P(F=F4|S==S3) = 0.3333333333333333
Probability of P(F=F5|S==S1) = 0.25
Probability of P(F=F5|S==S2) = 0.0
Probability of P(F=F5|S==S3) = 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
def string_features(A,B):
    l = S1.split()
    q=S2.split()
    lst=list()
    for f in l:
        if f not in q:
            lst.append(f)
    df=list()
    for a in q:
        if a not in l:
            df.append(a)
    r=0
    for o in l:
        if o in q:
            r+=1
    return r,lst,df
S1= "the first column F will contain only 5 uniques values "
S2= "the second column S will contain only 3 uniques values "
Q,W,E= string_features(S1,S2)
print(Q)
print(W)
print(E)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math
k= [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
fly=0
for i in k:
    a=i[0]
    b=i[1]
    fly+= (a*(math.log10(b))+((1-a)*(math.log10(1-(b)))))
value=(((fly)/8)*(-1))
print(value)


0.42430993457031635
